name: Mein Build Server Test

on: [push]

jobs:
  test-job:
    # Hier sagen wir GitHub, dass EXAKT Ihr neuer Runner genommen wird:
    runs-on: [self-hosted, docker-capable]

    steps:
      - name: Code aus dem Repository herunterladen
        uses: actions/checkout@v4

      - name: Prüfe die NodeJS Version auf meiner VM
        run: node -v

      - name: Prüfe ob Docker auf meiner VM funktioniert
        run: docker run hello-world
