name: Mein Build Server Test

on: [push]

jobs:
  test-job:
    # Hier achten wir exakt auf die Grossbuchstaben Ihrer VM:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Code aus dem Repository herunterladen
        uses: actions/checkout@v4

      - name: Prüfe die NodeJS Version auf meiner VM
        run: node -v

      - name: Prüfe ob Docker auf meiner VM funktioniert
        run: docker --version
